sudo: false
language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gatsby

install:
  - npm run build

script:
  - npm run start
  - npm run build


