version: "3.8"
services:
  app:
    command: npm run start -- --host 0.0.0.0
    environment:
      - INTERNAL_STATUS_PORT=8001
    image: node:14-alpine
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/usr/src/app:delegated
    working_dir: /usr/src/app
