version: "3.8"
services:
  app:
    command: npm run start -- --host 0.0.0.0
    image: node:14-alpine
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app:delegated
    working_dir: /usr/src/app
